_wandb:
    value:
        cli_version: 0.24.1
        e:
            3si2v6ebip8nx8ypjf8lbzq6zuyippuq:
                codePath: Src\2v2 Code.py
                codePathLocal: Src\2v2 Code.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "239411916800"
                        used: "232958734336"
                email: blackhawksrock9696@gmail.com
                executable: C:\Users\black\Documents\11111 Github Projects\Rocket League Modelling\Rocket-League-Bots\.venv\Scripts\python.exe
                git:
                    commit: 16222a7e2dcba6fd3464f03f8c0eb3524c07e859
                    remote: https://github.com/Zain4Rizvi/Rocket-League-Bots
                gpu: NVIDIA GeForce GTX 1660
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 1408
                      memoryTotal: "6442450944"
                      name: NVIDIA GeForce GTX 1660
                      uuid: GPU-4adf898b-7610-5ac7-0a05-10490b7b6c13
                host: ZainPC
                memory:
                    total: "33443192832"
                os: Windows-10-10.0.19045-SP0
                program: c:\Users\black\Documents\11111 Github Projects\Rocket League Modelling\Rocket-League-Bots\Src\2v2 Code.py
                python: CPython 3.10.19
                root: C:\Users\black\Documents\11111 Github Projects\Rocket League Modelling\Rocket-League-Bots
                startedAt: "2026-02-04T20:21:55.429915Z"
                writerId: 3si2v6ebip8nx8ypjf8lbzq6zuyippuq
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
            "4": 3.10.19
            "5": 0.24.1
            "8":
                - 3
            "10":
                - 20
            "12": 0.24.1
            "13": windows-amd64
critic_layer_sizes:
    value:
        - 512
        - 512
critic_lr:
    value: 5e-05
exp_buffer_size:
    value: 150000
gae_gamma:
    value: 0.99
gae_lambda:
    value: 0.95
min_inference_size:
    value: 7
n_proc:
    value: 8
policy_layer_sizes:
    value:
        - 512
        - 512
policy_lr:
    value: 5e-05
ppo_batch_size:
    value: 50000
ppo_clip_range:
    value: 0.2
ppo_ent_coef:
    value: 0.01
ppo_epochs:
    value: 1
ppo_minibatch_size:
    value: 50000
shm_buffer_size:
    value: 8192
standardize_obs:
    value: false
standardize_returns:
    value: true
timestep_limit:
    value: 1000000000
ts_per_iteration:
    value: 50000
